name: simple_code
description: Make Responsive and Development Faster and Easier
version: 2.0.1
author: Thize <thizeml@gmail.com>
homepage: https://github.com/thize/simple_code

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.bluebook.simple_code
    pluginClass: SimpleCodePlugin
